[package]
name = "comm_manager"
version = "0.0.0"
edition = "2018"

[dependencies]
rand = "0.8.5"

[dependencies.windows]
version = "0.56"
features = [
    "Win32_Foundation",
    "Win32_System_Pipes",
    "Win32_Storage_FileSystem",
    "Win32_Security",
]
